name: dls
channels:
  - pytorch
  - conda-forge
dependencies:
  - numpy
  - tqdm
  - scipy
  - scikit-learn
  - umap-learn
  - matplotlib
  - scikit-image
  - nibabel
  - matplotlib
  - pip
  - pip:
      - git+https://github.com/arekavandi/RobustPCA.git
      - git+https://github.com/arekavandi/utils_gradients.git
